/**
 * Spanish (Argentina) UI copy (interview-assistant "Spanish UI (v1)" + design
 * "Spanish (AR) strings"). Nested object — no i18n framework. Identifiers, keys
 * and code stay English; only the user-facing values are es-AR.
 *
 * STRING_KEYS is the authoritative registry of every key the UI references; the
 * strings unit test walks it to prove no rendered label is ever missing.
 */

export const strings = {
  app: {
    name: "Prompt Studio",
    tagline: "Estudio de fotografía asistido por IA. Todo local.",
  },
  nav: {
    studio: "Estudio",
    gallery: "Galería",
  },
  theme: {
    toggleLabel: "Cambiar tema",
    dark: "Oscuro",
    light: "Claro",
  },
  llm: {
    status: "Motor de IA",
    ready: "Listo",
    starting: "Arrancando…",
    offline: "Apagado",
    connected: "Conectado",
  },
  chat: {
    title: "Entrevista",
    subtitle: "Contame tu idea y te voy guiando.",
    welcome:
      "Hola, soy tu director de fotografía. Contame la foto que tenés en la cabeza y te hago un par de preguntas: el sujeto, la ropa, la luz y el estilo del encuadre.",
    placeholder: "Escribí tu idea acá…",
    send: "Enviar",
    stop: "Detener",
    sendDisabled: "El motor de IA todavía está arrancando, esperá un momento.",
    englishHint:
      "El prompt final va en inglés: es el idioma que ComfyUI entiende mejor. Igual lo podés editar antes de generar.",
    finalPromptLabel: "Prompt final (editable)",
  },
  chips: {
    label: "Sugerencias rápidas",
    axes: {
      subject: {
        label: "Sujeto",
        options: [
          "una mujer mayor tomando té en un patio sombreado",
          "una ciclista urbana en una esquina de Buenos Aires al amanecer",
        ],
      },
      clothing: {
        label: "Ropa",
        options: [
          "vestido de lino color crema y sombrero de paja",
          "saco de cuero y pañuelo de seda",
        ],
      },
      lighting: {
        label: "Luz y clima",
        options: [
          "luz dorada de atardecer bien suave",
          "luz dura de mediodía con sombras marcadas",
        ],
      },
      style: {
        label: "Estilo",
        options: [
          "estilo fotográfico natural, sin retocar demasiado",
          "estilo editorial con viñeta",
        ],
      },
    },
  },
  options: {
    title: "Opciones",
    advanced: "Avanzado",
    advancedHint: "Sampler, scheduler y semilla. Por lo general dejá la semilla en aleatoria.",
    steps: "Pasos",
    cfg: "CFG",
    seed: "Semilla",
    sampler: "Sampler",
    scheduler: "Scheduler",
    randomize: "Aleatoria",
    upscale: "Upscale HD",
  },
  aspect: {
    label: "Formato",
    custom: "Personalizado",
    width: "Ancho",
    height: "Alto",
  },
  variations: {
    label: "Variaciones",
    hint: "Cuántas imágenes distintas generamos (1 a 8).",
    tooMany: "Máximo 8 variaciones. Bajalo e intentá de nuevo.",
  },
  review: {
    title: "Revisión",
    promptLabel: "Prompt final",
    promptPlaceholder: "Edité el prompt final antes de generar…",
    promptRequired: "El prompt no puede estar vacío.",
    summary: "Resumen",
    resolution: "Resolución",
    prompt: "Prompt",
    parameters: "Parámetros",
    generate: "Generar",
    generating: "Generando…",
    busy: "Ya hay una generación en curso.",
    emptyTitle: "Todo listo para crear.",
    emptyHint: "Arrancá contando tu idea en el Estudio y volvé acá para perfeccionarla.",
  },
  progress: {
    title: "Generando",
    promptLabel: "Lo que pediste",
    variation: "Variación",
    queued: "En cola",
    started: "Arrancando",
    progress: "En proceso",
    complete: "Lista",
    failed: "Fallas",
    cancel: "Cancelar",
    cancelling: "Cancelando…",
    cancelled: "Cancelada",
    open: "Ver en la galería",
    total: "{actual}/{total} listas",
  },
  gallery: {
    title: "Galería",
    emptyTitle: "Todavía no generaste ninguna imagen.",
    emptyBody: "Arrancá una entrevista en el Estudio y tus tomas van a aparecer acá.",
    emptyCta: "Ir al Estudio",
    newRun: "Nueva",
    openDetail: "Ver detalle",
    promptExcerpt: "Prompt",
    params: "Parámetros",
    statusModel: "Estado",
    statusPrefix: "Estado",
    deleteRun: "Borrar",
  },
  detail: {
    back: "Volver a la galería",
    prompt: "Prompt",
    params: "Parámetros",
    seed: "Semilla",
    chatReplay: "Entrevista",
    compare: "Comparar",
    compareHint: "Elegí dos o más imágenes para verlas juntas.",
    selectAll: "Seleccionar comparables",
    regenerating: "Regenerando…",
    regenerate: "Regenerar",
    keepSeed: "Mantener la semilla",
    delete: "Borrar",
    deleting: "Borrando…",
    deleteConfirm: "¿Borrar esta generación y sus archivos?",
    confirmDelete: "Sí, borrar",
    cancel: "Cancelar",
    noChat: "Esta generación no guardó la conversación.",
    images: "Imágenes",
  },
  errors: {
    generic: "Algo salió mal. Reintentá en un momento.",
    "400": "Revisá los datos del formulario e intentá de nuevo.",
    "404": "No encontramos eso. Tal vez se borró.",
    "409": "Ya hay una generación en curso. Esperá a que termine e intentá de nuevo.",
    "422": "El prompt no se pudo convertir. Revisalo e intentá de nuevo.",
    "500": "Ocurrió un error en el servidor. Mirá la consola e intentá de nuevo.",
    "502": "ComfyUI está apagado. Abrí el launcher y tocá 'Reintentar'.",
    "503": "El motor de IA todavía está arrancando… esperá un momento.",
    retry: "Reintentar",
  },
  statusBadge: {
    pending: "En cola",
    running: "Generando",
    completed: "Completado",
    failed: "Falló",
    cancelled: "Cancelado",
  },
} as const;

/**
 * Same object re-exported via a getter used by tests; STRING_KEYS is the
 * canonical dotted-path list every UI reference must resolve to.
 */
export const STRING_KEYS = [
  "app.name",
  "app.tagline",
  "nav.studio",
  "nav.gallery",
  "theme.toggleLabel",
  "theme.dark",
  "theme.light",
  "llm.status",
  "llm.ready",
  "llm.starting",
  "llm.offline",
  "llm.connected",
  "chat.title",
  "chat.subtitle",
  "chat.welcome",
  "chat.placeholder",
  "chat.send",
  "chat.stop",
  "chat.sendDisabled",
  "chat.englishHint",
  "chat.finalPromptLabel",
  "chips.label",
  "chips.axes.subject.label",
  "chips.axes.subject.options",
  "chips.axes.clothing.label",
  "chips.axes.clothing.options",
  "chips.axes.lighting.label",
  "chips.axes.lighting.options",
  "chips.axes.style.label",
  "chips.axes.style.options",
  "options.title",
  "options.advanced",
  "options.advancedHint",
  "options.steps",
  "options.cfg",
  "options.seed",
  "options.sampler",
  "options.scheduler",
  "options.randomize",
  "options.upscale",
  "aspect.label",
  "aspect.custom",
  "aspect.width",
  "aspect.height",
  "variations.label",
  "variations.hint",
  "variations.tooMany",
  "review.title",
  "review.promptLabel",
  "review.promptPlaceholder",
  "review.promptRequired",
  "review.summary",
  "review.resolution",
  "review.prompt",
  "review.parameters",
  "review.generate",
  "review.generating",
  "review.busy",
  "review.emptyTitle",
  "review.emptyHint",
  "progress.title",
  "progress.promptLabel",
  "progress.variation",
  "progress.queued",
  "progress.started",
  "progress.progress",
  "progress.complete",
  "progress.failed",
  "progress.cancel",
  "progress.cancelling",
  "progress.cancelled",
  "progress.open",
  "progress.total",
  "gallery.title",
  "gallery.emptyTitle",
  "gallery.emptyBody",
  "gallery.emptyCta",
  "gallery.newRun",
  "gallery.openDetail",
  "gallery.promptExcerpt",
  "gallery.params",
  "gallery.statusModel",
  "gallery.statusPrefix",
  "gallery.deleteRun",
  "detail.back",
  "detail.prompt",
  "detail.params",
  "detail.seed",
  "detail.chatReplay",
  "detail.compare",
  "detail.compareHint",
  "detail.selectAll",
  "detail.regenerating",
  "detail.regenerate",
  "detail.keepSeed",
  "detail.delete",
  "detail.deleting",
  "detail.deleteConfirm",
  "detail.confirmDelete",
  "detail.cancel",
  "detail.noChat",
  "detail.images",
  "errors.generic",
  "errors.400",
  "errors.404",
  "errors.409",
  "errors.422",
  "errors.500",
  "errors.502",
  "errors.503",
  "errors.retry",
  "statusBadge.pending",
  "statusBadge.running",
  "statusBadge.completed",
  "statusBadge.failed",
  "statusBadge.cancelled",
] as const;

/** Shape the STRING_KEYS entries are validated against. */
export type StringKey = (typeof STRING_KEYS)[number];